### ISSUE TITLE
Hello, hyp3_isce is running in the cloud or on one's own computer? Can I set -- azimuth looks 1-- range looks 5?

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3-isce2#102]
Hello, hyp3_isce is running in the cloud or on one's own computer? Can I set -- azimuth looks 1-- range looks 5?

**Comment by asjohnston-asf** [comment]
This application is under active development. You can install it on your own computer using the [Developer Setup](https://github.com/ASFHyP3/hyp3-isce2#developer-setup) instructions in the README. It's not currently available via cloud processing. You can search for burst products advertised in [Vertex](https://search.asf.alaska.edu/#/?dataset=SENTINEL-1%20BURSTS) and use the names of those products when running `insar_tops_burst`.

Yes, as of [v0.4.0](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/CHANGELOG.md#040) the `insar_tops_burst` workflow includes a `--looks` option that can be set to any of `20x4`, `10x2`, or `5x1`.
```
$ insar_tops_burst --help

usage: insar_tops_burst [-h] [--bucket BUCKET] [--bucket-prefix BUCKET_PREFIX] [--looks {20x4,10x2,5x1}] granules [granules ...]

Create a single-burst Sentinel-1 geocoded unwrapped interferogram using ISCE2's TOPS processing workflow

positional arguments:
  granules

options:
  -h, --help            show this help message and exit
  --bucket BUCKET       AWS S3 bucket HyP3 for upload the final product(s) (default: None)
  --bucket-prefix BUCKET_PREFIX
                        Add a bucket prefix to product(s) (default: )
  --looks {20x4,10x2,5x1}
                        Number of looks to take in range and azimuth (default: 20x4)
```

**Comment by ZGHHGZ** [comment]
> This application is under active development. You can install it on your own computer using the [Developer Setup](https://github.com/ASFHyP3/hyp3-isce2#developer-setup) instructions in the README. It's not currently available via cloud processing. You can search for burst products advertised in [Vertex](https://search.asf.alaska.edu/#/?dataset=SENTINEL-1%20BURSTS) and use the names of those products when running `insar_tops_burst`.
> 
> Yes, as of [v0.4.0](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/CHANGELOG.md#040) the `insar_tops_burst` workflow includes a `--looks` option that can be set to any of `20x4`, `10x2`, or `5x1`.
> 
> ```
> $ insar_tops_burst --help
> 
> usage: insar_tops_burst [-h] [--bucket BUCKET] [--bucket-prefix BUCKET_PREFIX] [--looks {20x4,10x2,5x1}] granules [granules ...]
> 
> Create a single-burst Sentinel-1 geocoded unwrapped interferogram using ISCE2's TOPS processing workflow
> 
> positional arguments:
>   granules
> 
> options:
>   -h, --help            show this help message and exit
>   --bucket BUCKET       AWS S3 bucket HyP3 for upload the final product(s) (default: None)
>   --bucket-prefix BUCKET_PREFIX
>                         Add a bucket prefix to product(s) (default: )
>   --looks {20x4,10x2,5x1}
>                         Number of looks to take in range and azimuth (default: 20x4)
> ```

![image](https://github.com/ASFHyP3/hyp3-isce2/assets/88225620/70868a2c-601d-4a08-a420-70f413b90741)

**Comment by jtherrmann** [comment]
Hi @ZGHHGZ, let's continue troubleshooting this error at https://github.com/ASFHyP3/tutorials/issues/8. Thanks!
