### ISSUE TITLE
GitHub Actions fails to push `hyp3-isce2` image to GHCR with `403 Forbidden` (again)

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-isce2#136]
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-2191

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

The `dockerize` workflow is failing for https://github.com/ASFHyP3/hyp3-isce2/pull/134 with the following error:

```
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/asfhyp3/hyp3-isce2:0.7.2.dev2_gb21307f: unexpected status from POST request to https://ghcr.io/v2/asfhyp3/hyp3-isce2/blobs/uploads/: 403 Forbidden
```

This is very similar to https://github.com/ASFHyP3/hyp3-isce2/issues/120, where the error was as follows:

```
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/asfhyp3/hyp3-isce2:0.6.2.dev5_g3db5604: unexpected status: 403 Forbidden
```

Since the previous issue seemed to resolve itself, I figured this one would, too. But the workflow has now been failing for about a week over several different re-runs, so we should probably try to debug it. Might be worth revisiting the steps that I took in my attempts to debug the previous issue.

**Comment by jtherrmann** [comment]
Inspecting the logs for https://github.com/ASFHyP3/hyp3-isce2/actions/runs/6004893749/job/16558054441?pr=134 I noticed that under the `Set up Docker Buildx` step (defined [here](https://github.com/ASFHyP3/actions/blob/develop/.github/workflows/reusable-docker-ghcr.yml)) there are errors under `Booting builder`:

```
  #1 21.39 error: failed to list workers: Unavailable: connection error: desc = "transport: error while dialing: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory"
```

```
Error:    Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/buildx_buildkit_builder-bc3fa86a-28c5-46bd-87ed-eb905bf2f0db0/json": context deadline exceeded
```

I also re-opened https://github.com/ASFHyP3/hyp3-isce2/pull/121 (a dummy PR that I previously used to debug this issue) and the dockerize workflow succeeded [here](https://github.com/ASFHyP3/hyp3-isce2/actions/runs/6101550102/job/16558160792?pr=121). I don't see any errors under `Booting builder` in the logs. So I suspect that the `403` error is related to the `Booting builder` errors.

However, before attempting to debug those errors, I want to see if I can just get the failing dockerize workflow to succeed for the dependabot version bump, either by closing and re-opening the PR, or manually opening a PR to make the same changes. I suspect that there is something wrong with the GitHub Actions instance being used to run the dockerize workflow for that PR, so if we can get it to run on a different instance, it should succeed.

**Comment by jtherrmann** [comment]
Yep, closing and re-opening the PR allowed the dockerize workflow to succeed.

**Comment by jtherrmann** [comment]
Interestingly, https://github.com/ASFHyP3/hyp3-isce2/pull/135 is also failing for dockerize with a `403` error (see [here](https://github.com/ASFHyP3/hyp3-isce2/actions/runs/6077426552/job/16487106741?pr=135)) but I see no errors under `Booting builder` in the logs. I will first try updating the branch (merging `develop` back in) and if that doesn't allow the dockerize job to succeed, I'll try closing and re-opening the PR.

**Comment by jtherrmann** [comment]
Updating the branch did the trick.

**Comment by jtherrmann** [comment]
To conclude, the `403` error has resolved itself as it did last time, but in the future, if re-running the failed job doesn't work, then we should try closing the PR / deleting the branch, then restoring the branch / re-opening the PR. If that doesn't work, my next step would be to create a new branch with identical changes and open a new PR. The goal is to get the workflow to run in a brand-new environment, as I suspect there is something wrong with the underlying GitHub Actions runner (virtual machine) in the cases where the `403` error persists across multiple job re-runs.

**Comment by jhkennedy** [comment]
@jtherrmann is it worth investigating other docker setup/build actions? Could it just be a Buildx problem?

**Comment by jtherrmann** [comment]
@jhkennedy Maybe, though I believe I was noticing some other actions failing with HTTP errors around the same time, so it could just be a GitHub Actions problem. Let's wait and see if it continues to be a nuisance.
