### ISSUE TITLE
Name at burst processing

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3-isce2#166]
The news that hpy3-sdk supports burst processing with ISCE in the new release is encouraging, but currently the only burst data that can be searched on the ASF website is from June 2023 onwards, with fewer burst sequences, making it difficult to support Time-Series InSAR processing (only some of the test regions have long time-series bursts).
I would like to know when the full burst numbering will be available, or if another method can be added to temporarily replace the current burst numbering until the full burst numbering feature is implemented, i.e., uploading a mission by the number of the whole view image, the strip number, and the burst sequence number, which was available in the previous version of HYP3-ISCE2.
As far as I know, getting the number, strip number, and burst serial number of the whole view image of a burst at the same location is complicated, I found a way and tested it, it had some errors, I modified it, after I tested the method by processing it many times on my local computer, the modified method has no errors so far, hopefully this can be an before burst numbering is completely overwritten An alternative way, unfortunately at the moment I can't upload the task with this whole view image numbering, strip numbering, and burst serial numbering method.

https://nbviewer.org/github/relativeorbit/hyp3bursts/blob/main/workflow-ascending.ipynb

modified：
https://github.com/ZGHHGZ/Single-Burst-Processing-Flow/blob/main/SBPF/code/hyp3_isce2_start.ipynb

**Comment by khogenso** [comment]
Hello ZGHHGZ, you are right that the burst population is sparse right now.  We halted population in order to make some improvements, and are getting ready to restart the population.  The schedule currently is for population to restart in early January, and is expected to take 3-6 months.

I don't have any good suggestions on determining the burst IDs manually unfortunately.  If you have areas over which you'd like to see burst metadata population prioritized, please let us know and we'll do our best to accommodate.

Thanks for your patience on this - we're excited to be able to offer this service and appreciate any feedback as you use it!

**Comment by ZGHHGZ** [comment]
> Hello ZGHHGZ, you are right that the burst population is sparse right now. We halted population in order to make some improvements, and are getting ready to restart the population. The schedule currently is for population to restart in early January, and is expected to take 3-6 months.
> 
> I don't have any good suggestions on determining the burst IDs manually unfortunately. If you have areas over which you'd like to see burst metadata population prioritized, please let us know and we'll do our best to accommodate.
> 
> Thanks for your patience on this - we're excited to be able to offer this service and appreciate any feedback as you use it!


**_If you have areas over which you'd like to see burst metadata population prioritized, please let us know and we'll do our best to accommodate._**
@khogenso 
‘S1_303065_IW2_20231227T101307_VV_3E9B-BURST’
↑     ↑     ↑     ↑     ↑     ↑     ↑     ↑     ↑     ↑     ↑     ↑     ↑     
At the moment, I want to do timing processing for this burst region, can you be the first to update this region.
I appreciate your support very much.

**Comment by asjohnston-asf** [comment]
FYI, the geometry for that burst is `POLYGON((116.2475 35.5056,116.289 35.3215,116.7953 35.3938,117.2738 35.4599,117.2329 35.6523,116.7541 35.5821,116.2475 35.5056))`; I see 254 ascending SLCs and another 51 descending SLCs in that region.

[view these SLCs in Vertex](https://search.asf.alaska.edu/#/?polygon=POLYGON((116.2475%2035.5056,116.289%2035.3215,116.7953%2035.3938,117.2738%2035.4599,117.2329%2035.6523,116.7541%2035.5821,116.2475%2035.5056))&searchType=Geographic%20Search&resultsLoaded=true&zoom=6.596&center=115.249,31.711&productTypes=SLC)
