### ISSUE TITLE
Matching Hosted Hyp3 Outputs Locally

### ISSUE THREAD

**Issue by scottyhq** [ASFHyP3/hyp3-isce2#175]
### Background
Running hyp3-isce2 (0.9.2) via ASF's hosted hyp3 service is fantastic. I also like that there is an option to run the workflow locally via conda or Docker. But I'm not sure how to obtain an identical output running locally. In particular it seems the final formatting step is coming from a separate workflow? 
`translate_outputs: Convert the outputs of hyp3-isce2 to hyp3-gamma formatted geotiff files` 

### Describe the solution you'd like
Document someplace how to get the same output locally

**Comment by jhkennedy** [comment]
Hi @scottyhq! When HyP3 runs a plugin, it's effectively doing a `docker run` of this repository's docker image.

For an `INSAR_ISCE_BURST` job definition (that you'd POST to the HyP3 API) looks like this:
```json
    {
      "job_parameters": {
        "granules": [
          "S1_136231_IW2_20200604T022312_VV_7C85-BURST",
          "S1_136231_IW2_20200616T022313_VV_5D11-BURST"
        ],
        "apply_water_mask": false,
        "looks": "20x4"
      },
      "job_type": "INSAR_ISCE_BURST",
      "name": "example"
    }
 ```
 That will get translated into a docker run command like:
 ```shell
docker run -it --rm \
    -e EARTHDATA_USERNAME=... \
    -e EARTHDATA_PASSWORD=... \
    -e ESA_USERNAME=... \
    -e ESA_PASSWORD=... \
    ghcr.io/asfhyp3/hyp3-isce2:0.9.2 ++process insar_tops_burst \
    --looks 10x2 \
   --apply-water-mask False
```

Which should be the same as running:
```shell
python -m hyp3_isce2 ++process insar_tops_burst \
    --looks 10x2 \
   --apply-water-mask False
```

In the code, by using some [argparse and entrypoint magic](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/__main__.py#L14), that's running the [HyP3 `insar_tops_burst` entrypoint](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/pyproject.toml#L61), which calls this function:
https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L443-L547

For the format conversion, that's called here:
https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L500

And runs this function:
https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L300-L399

Assuming you're running `hyp3_isce2.insar_tops_burst.main`, the only thing I can think of that'd lead to different results in HyP3 vs locally is dependency differences in your local environment vs the container, which was created/frozen when we built the container image.

**Comment by scottyhq** [comment]
🤦 Sorry for the noise @jhkennedy you are of course correct. In my haste I was misremembering and went directly to the `merged/` folder rather than ` S1_136231_IW2_20200604_20200616_VV_INT80_8EC4` which is created by the scripts you've helpfully identified.

The only remaining piece of the puzzle for me is if running this via docker but *not* the hyp3 api. How to preserve the outputs. I see two solutions: 

1. Add a named volume mount (--mount source=hyp3isce2,target=/home/conda). As an aside this doesn't work for a local volume mount (-v $PWD:/home/conda) because it overwrites home config files and therefore `conda init` doesn't work ... i can create a separate issue for that

2. Modify https://github.com/ASFHyP3/hyp3-isce2/blob/5713e162728b9e2b87d8ddc61c2a37de8183b406/src/hyp3_isce2/etc/entrypoint.sh#L3 to include a post-processing step of uploading to a bucket or some other storage

**Comment by jhkennedy** [comment]
@scottyhq you hit on both of the possible solutions:

1. Write to local disk: our plugins should just write to whatever is the current working directory, so you can do ` -v ${PWD}:/work -w /work` to mount in a working directory and set it as the current working directory. If that doesn't work I'd consider it a bug!

2. upload to an AWS bucket: the HyP3 entrypoint's final step is to [upload to a bucket + prefix](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L540-L547) if you provide the `--bucket` argument (`--bucket-prefix` is optional). To do that with the docker container, you'll want to add your credentials via env variables or I often just mount in my `.aws` directory and set the profile I want to use via an env variable `-v ${HOME}/.aws:/home/conda/.aws -e AWS_PROFILE=sandbox`. The docker command would then look like:
   ```shell
   docker run -it --rm \
   -v ${HOME}/.aws:/home/conda/.aws \
   -e AWS_PROFILE=... \
   -e EARTHDATA_USERNAME=... \
   -e EARTHDATA_PASSWORD=... \
   -e ESA_USERNAME=... \
   -e ESA_PASSWORD=... \
   ghcr.io/asfhyp3/hyp3-isce2:0.9.2 ++process insar_tops_burst \
   --looks 10x2 \
   --apply-water-mask False \
   --bucket ... \
   --bucket-prefix ...
   ```
  
  Notably, this will upload both the `.zip` product directory to your prefix, and also everything inside the zip next to it. We double-store everything so you can have direct access to the parts and conveniently download the zip.

**Comment by jhkennedy** [comment]
> `-v $PWD:/tmp -w /tmp` works. I can add a note to the README if that is helpful.

Ha, got it faster than I could reply! Yes, A note to the readme would be great!
