### ISSUE TITLE
Instructions for trying this plugin

### ISSUE THREAD

**Issue by scottyhq** [ASFHyP3/hyp3-isce2#28]
### Background

Hi! I'm working with several students at UW who have been working with HYP3 (thank you it is a wonderful resource for the research community). But we'd like to try ISCE2 processing for some projects. This seems to be a place where we could testing things out and contribute. 

But it's unclear to me from the docs if you need to deploy your own HYP3 to use this (https://hyp3-docs.asf.alaska.edu/plugins/)

 ### Additional context

We have our own AWS account if needed.

**Comment by forrestfwilliams** [comment]
Hey @scottyhq this plugin is in the Alpha stage, but we are hoping to add some running instructions to the README soon.

For context, we're currently focused on developing a burst-based InSAR workflow within this plugin and there is still a lot left to do. In particular, the interface is not stable and the method we use to download burst data will likely change drastically once the actual Sentinel-1 burst collection becomes available in [CMR](https://www.earthdata.nasa.gov/eosdis/science-system-description/eosdis-components/cmr).

That said, we are excited about supporting other science workflows within this plugin! Currently, we're working with [AVO](https://www.avo.alaska.edu) to add in their workflows. In the next couple of days we're going to be opening a PR that sets up the structure for adding additional workflows and we'll be walking AVO through that process. We'd be happy to do the same for you.

Also, it's important to note that this repository borrows heavily from [DockerizedTopsApp](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp), which produces the ARIA-S1-GUNW products. This repository is much more mature and could also be useful to you.

Let us know if you're interested or have any questions. We'd definitely enjoy work with you!

**Comment by jhkennedy** [comment]
@scottyhq I'll add that this plugin/work is part of a larger strategy to move to fully open-source workflows. So, we have on our production HyP3 road map:
1. Providing Burst-based S1 products that are very similar to our current GAMMA based products
1. Providing S1 products that are very similar to our current GAMMA based products
1. Providing ARIA-S1-GUNW products, both to
   * build out a user-gernerate archive of standard products
   * allow customization of those products
1. Providing burst-based ARIA-S1-GUNW products

We don't expect to sunset the GAMMA-based products anytime in the foreseeable future, but there's a lot of value in providing fully-open workflows for the community. 

Let us know if you'd like to be involved in any of the above!

**Comment by scottyhq** [comment]
> Also, it's important to note that this repository borrows heavily from [DockerizedTopsApp](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp), which produces the ARIA-S1-GUNW products. This repository is much more mature and could also be useful to you.

Thanks! I don't know how I missed that. Looking at the README It's still not clear to me how we might run that workflow via HyP3, which is what we'd ultimately like to do since we don't necessarily have access to a machine with lots of storage and CPUs (seems we'd need access to a custom deployment of HyP3)?

> Let us know if you'd like to be involved in any of the above!

The roadmap seems great! I think burst products will be fantastic, as does prioritizing standard product creation with a fully open source processor. 

In the short term, I'm working with students who want to be able to *quickly* generate a set of interferograms over an area of interest where GUNWs do not currently exist. It is important to be able to 1. customize resolution of processing and 2. create ionospheric corrections, so that is why we are using ISCE2.

**Comment by jhkennedy** [comment]
>  Looking at the README It's still not clear to me how we might run that workflow via HyP3

Yes, @scottyhq, we haven't really documented this well yet. Overall, the HyP3 + Plugin integration follows this contract:

* The plugin is fundamentally a docker container that we expect:
  * to be self-contained -- it shouldn't matter *where* it's run so needs to handle all data marshaling etc. itself
  * it will produce a "product" (or products) which are uploaded to AWS S3 at the end of the workflow
  * The registered [docker entry point](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/Dockerfile#L47) is the hyp3 workflow and all parameters needed are passed as [CMD](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/Dockerfile#L48)s (command line parameters to a docker run command)
  
* HyP3 then simply needs to know:
  * the docker image to run
  * the parameters to the docker run command to provide
  * the resource requirements
  * any required secrets
  * what parameters to provided in the API
  
---

So, for DockerizedTopsApp, that looks like:

* The plugin will be called with a docker run command like:
  ```shell
  docker run -it --rm ghcr.io/access-cloud-based-insar/dockerizedtopsapp:latest \
      --bucket [BUCKET] --bucket-prefix [BUCKET_PREFIX]  \  # Provided by HyP3
      --reference-scenes [SCENE [SCENE] ...] \
      --secondary-scenes [SCENE [SCENE] ...] 
  ```
  and upload the GUNW product to `s3://[BUCKET]/[BUCKET_PREFIX]/[PRODUCT_FILE]`.
  
* That is all specified to HyP3 in a YAML [job specification](https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE.yml) file:
  * the docker image: https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE.yml#L45
  * the docker run parameters: https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE.yml#L47-L54
  * resource requirements: https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE.yml#L55-L57
  * specifying the parameters available in the HyP3 API using the [OpenAPI spec](https://swagger.io/docs/specification/about/): https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE.yml#L5-L42

**Comment by jhkennedy** [comment]
It is important to be able to 1. customize resolution of processing and 2. create ionospheric corrections, so that is why we are using ISCE2.

@scottyhq for the ARIA-S1-GUNW, both of those are on the roadmap! The v3 products, which are coming *very* soon, will allow ionosphere correction:
* https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE_TEST.yml#L37-L41

And customizable resolution is next up on the road map.

**Comment by scottyhq** [comment]
Awesome, thanks for all this information @jhkennedy I'm starting to wrap my head around how it all works. I have a few follow-ups :) 

> for things not available yet in "production" HyP3

How to I know what is currently available? I'm surprised conda or pip install gets a client version 2.0.1, but there are lots of hyp3 releases showing up here https://github.com/ASFHyP3/hyp3/releases . Is there some way to access a development deployment rather than 'https://hyp3-api.asf.alaska.edu/' for testing the hyp3-isce jobs?

> You could deploy HyP3 into your own AWS account if you have "admin" access 

This would be preferable as we have lots of AWS credits!

> Notably, all our custom deployments will work with [Vertex](https://github.com/ASFHyP3/hyp3-isce2/issues/search.asf.alaska.edu)... There are two parts that we'll have to help you with though:

So I gather the DNS bit is optional if forgoing vertex integration? We generally want to script the whole setup rather than going through the vertex gui. Basically the approach in the docs: https://nbviewer.org/github/ASFHyP3/hyp3-sdk/blob/main/docs/sdk_example.ipynb

**Comment by jhkennedy** [comment]
> > for things not available yet in "production" HyP3
> How to I know what is currently available?

The best source is our products page in our documentation:
* https://hyp3-docs.asf.alaska.edu/products/

But also, the API itself will tell you:
* https://hyp3-api.asf.alaska.edu/ui/
   ![image](https://user-images.githubusercontent.com/7882693/232167705-91c23623-105d-49f8-82f1-2509f19c389d.png)

> I'm surprised conda or pip install gets a client version 2.0.1, but there are lots of hyp3 releases showing up here https://github.com/ASFHyP3/hyp3/releases 

Yeah. Our practice currently is that the HyP3 SDK is versioned independently of the HyP3 platform, and the release notes / changelog is specific to the repository. I def. could see value in keeping the versions in sync...

> Is there some way to access a development deployment rather than 'https://hyp3-api.asf.alaska.edu/' for testing the hyp3-isce jobs?

Yes, technically. It's currently available at https://hyp3-test-api.asf.alaska.edu, which you would have a quota in. We don't generally advertize that as (1) we don't have a tone of $$ allocated to the test deployment and (2) we make **no** guarantees about that deployment working or anything about it being preserved -- it's mostly for our internal testing purposes. 

You can use a custom deployment just fine from Vertex and/or the HyP3 SDK by changing:
* Vertex: the backend URL in your user preference
  ![image](https://user-images.githubusercontent.com/7882693/232168399-7e14836a-5f1b-4142-92e9-2f8ff857fb1c.png)
* SDK: the API URL when you instantiate the HyP3 class
  ```python
  import hyp3_sdk as sdk
  
  hyp3 = sdk.HyP3('https://hyp3-test-api.asf.alaska.edu')
  ```
  
:exclamation:  **However** :exclamation: , Vertex won't allow you to *submit* non-production job types (view/download all works), so you'll have to use a job definition dictionary and the `submit_prepared_jobs` method in the SDK. For the INSAR_ISCE_TEST job type, that'd look like:
  ```python
import copy

import hyp3_sdk as sdk

hyp3 = sdk.HyP3('https://hyp3-test-api.asf.alaska.edu')

job_definition = {
    "name": "Job Name",
    "job_type": "INSAR_ISCE_TEST",
    "job_parameters": {
        "compute_solid_earth_tide": False,
        "esd_coherence_threshold": -1,
        "estimate_ionosphere_delay": False,
        "frame_id": -1,
        "weather_model": "None"
    },
}

list_of_reference_granules = [
    # list of lists!
    ["S1B_IW_SLC__1SDV_20210723T014947_20210723T015014_027915_0354B4_B3A9",]
]
list_of_secondary_granules = [
    # list of lists!
    ["S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404",]
]

prepared_jobs = []
for reference_granules, secondary_granules in zip(list_of_reference_granules, list_of_secondary_granules):
    job = copy.deepcopy(job_definition)
    job['job_parameters']['granules'] = reference_granules
    job['job_parameters']['secondary_granules'] = secondary_granules
    prepared_jobs.append(job)

jobs = hyp3.submit_prepared_jobs(prepared_jobs)

jobs = hyp3.watch(jobs)
  ```
  
Or, a more detailed notebook for our water map jobs in `hyp3-watermap`: 
https://github.com/ASFHyP3/asf-tools/blob/develop/prototype/water-extent-map-on-demand.ipynb

**Comment by jhkennedy** [comment]
> > You could deploy HyP3 into your own AWS account if you have "admin" access
> This would be preferable as we have lots of AWS credits!

@scottyhq I'd be happy if you tried it -- with or without us helping you with the process. We've not really had anyone do it on their own without us in the loop.

> So I gather the DNS bit is optional if forgoing vertex integration? We generally want to script the whole setup rather than going through the vertex gui. Basically the approach in the docs: https://nbviewer.org/github/ASFHyP3/hyp3-sdk/blob/main/docs/sdk_example.ipynb

Not really, our whole auth mechanism on the Hyp3 side also uses the same vertex cookie and expects an ASF DNS name. That was more the motivation for the decision. 

You can play the `/etc/hosts` game to spoof it if you want, but without a (likely) significant amount of dev. time to drop or re-work the auth, that's a requirement.

I don't see why we couldn't set up a DNS name and cut you a specific cert for it which you can upload to your AWS account (I'd have to check with he platform team... they might not be comfortable with the latter part if we didn't have AWS account access for auditing purposes).

That said, the API is really just a thin wrapper around a DynamoDB table -- you could just skip/ignore the API and post jobs to, and get job info from, the table directly. You'll miss all the validation though and basically have to build a `boto3` focused version of the HyP3 SDK.

**Comment by jhkennedy** [comment]
> I quickly tried modifying your example of using INSAR_ISCE_TEST which failed, going just passed the timeout 21600 (jobid f258c8a3-6763-49e6-afae-8687cdb7aed6).

yep, looks like the timeout needs to be adjusted. We just doubled the timeout on the production version of the job when ionosphere correction and esd, but haven't done a mini-campaign yet to determine timouts and resource requirements. @cmarshak have you also seen INSAR_GAMMA_TEST jobs fail due to timeout? Any thoughts on a better timeout? I've opened ASFHyP3/hyp3#1582 to increase the timeout (some additional context/discussion there).

> As far as I can tell, the computational requests and timeout cannot be adjusted by users?:

@scottyhq that's correct -- we typically do a cost optimization study to lock in the most efficient instances available to the compute environment and use the resource requirements to pack jobs effectively.

**Comment by cmarshak** [comment]
> yep, looks like the timeout needs to be adjusted. We just doubled the timeout on the production version of the job when ionosphere correction and esd, but haven't done a mini-campaign yet to determine timouts and resource requirements. @cmarshak have you also seen INSAR_GAMMA_TEST jobs fail due to timeout? Any thoughts on a better timeout? I've opened https://github.com/ASFHyP3/hyp3/pull/1582 to increase the timeout (some additional context/discussion there).

I haven't used GAMMA. There is a lot here in terms of the conversation so I hope I am following. For INSAR_ISCE jobs, I will say ESD is an extremely expensive, long-running process. We exposed that parameter to allow for experimentation later, but don't anticipate to use it. Also, unless you know ESD is present it will introduce errors from what I understand: https://github.com/isce-framework/isce2/issues/620

Currently, @mgorvorcin is working on developing some semi-operational ionosphere layers that would help with this that can run within the constraints: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/130

We are also developing lots of tools to submit jobs to hyp3 using are INSAR_ISCE jobs. We are about to process the main Continental US coastline. I have to put it up. Here are some examples of submitting a time series: https://github.com/ACCESS-Cloud-Based-InSAR/s1-frame-enumerator/blob/dev/notebooks/Submitting_to_Hyp3.ipynb

Above, we have developed fix spatial frames to more easily enumerate IFGs.

I would definitely encourage at some point reaching out to @dbekaert about this in case there are synergies since we have a bunch of hyp3 deployments that we already manage at JPL.

We are also have some of the custom items in this PR: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/122

I think @dbekaert and @jhkennedy have to determine how this variable resolution and additional layers will be standardized/distributed.

**Comment by jhkennedy** [comment]
@cmarshak my bad, I made a typo. @scottyhq specifically submitted an `INSAR_ISCE_TEST` job (not GAMMA) with esd off and ionosphere on and hit the timeout.

**Comment by forrestfwilliams** [comment]
@scottyhq does the current readme provide the instructions you need? Wondering if we can close this issue.

**Comment by forrestfwilliams** [comment]
Sounds good! Glad that it's usable from your end!
