### ISSUE TITLE
Finish following the `hyp3-cookiecutter` docs

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-isce2#3]
I left off at <https://github.com/ASFHyP3/hyp3-cookiecutter/tree/update_staging#7-restart-the-github-actions> after merging https://github.com/ASFHyP3/hyp3-isce2/pull/1 and https://github.com/ASFHyP3/hyp3-isce2/pull/2. The second PR was to fix what I *thought* was a typo in `hyp3-cookiecutter` [here](https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.__project_name%7D%7D/.github/workflows/test-and-build.yml#L34) but now I don't know if that was actually a typo.

The [`dockerize` job](https://github.com/ASFHyP3/hyp3-isce2/actions/runs/4516050470/jobs/7954073481) is currently failing with:

```
ERROR: failed to solve: failed to push ghcr.io/asfhyp3/hyp3-isce2:0.0.1.dev4_g999cdf6: unexpected status: 403 Forbidden
```

TODO:

- [x] Solve the perms issue.
- [x] Revert https://github.com/ASFHyP3/hyp3-isce2/pull/2
- [x] Finish following the `hyp3-cookiecutter` docs.

**Comment by forrestfwilliams** [comment]
Yeah I think this behavior is unique to the weirdness I created by first creating then deleting a repository with the same name.
