### ISSUE TITLE
Clean up logging

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-isce2#53]
From @asjohnston-asf:

> not getting log output, only isce output, I think because https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L30 sets `log` to the module logger, and https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L193 only configures the root logger
>
> we have a mix of `log = logging.getLogger()` and `log = logging.getLogger(__name__)` in hyp3-gamma, I remember it being a mess to clean up there when I refactored RTC and I don't recall if we ever cleaned up InSAR

**Comment by jtherrmann** [comment]
Actually, configuring the root logger also configures all the child loggers. What we have *should* work, except it seems that the root logger is already configured. From https://docs.python.org/3/library/logging.html#logging.basicConfig:

>This function does nothing if the root logger already has handlers configured, unless the keyword argument _force_ is set to `True`.

I confirmed that setting `force=True` makes logging work. But if the root logger has already been configured, maybe we don't want to mess with it. So still deciding on the best solution.

**Comment by jtherrmann** [comment]
Hmm, that fixed the level issue, but it seems the root logger still has a pre-existing configuration so that `basicConfig` only works with `force=True`.

**Comment by jtherrmann** [comment]
Alright, I got way too curious about where the root logger was being configured, but I tracked it down to here: https://github.com/isce-framework/isce2/blob/a5630c12030c6ffc7e5f4106471a3e7a9961b438/__init__.py#L37-L39

The formatter is specified here: https://github.com/isce-framework/isce2/blob/a5630c12030c6ffc7e5f4106471a3e7a9961b438/defaults/logging/logging.conf#L32

For future reference, I tracked it down by configuring the root logger at the beginning of our code:

```python3
logging.basicConfig(stream=sys.stdout, format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)
```

And then strategically placing `logging.info` calls until I found the exact `import` statement that was causing the log record format to change:

```python3
from isce.applications.topsApp import TopsInSAR
```

Anyway, now that my curiosity is satisfied, I think that either forcing our own logging configuration or just using the `isce2` configuration would both be reasonable options.

**Comment by jtherrmann** [comment]
It would also be reasonable to call [`Logger.addHandler`](https://docs.python.org/3/library/logging.html#logging.Logger.addHandler) to add a custom handler (with a custom formatter) to our module logger, but we would also have to set [`propagate`](https://docs.python.org/3/library/logging.html#logging.Logger.propagate) to `False`, to prevent events from being handled both by our module logger and the root logger (which results in events being logged twice). Whereas if we do not add a custom handler to our module logger, then events will only be handled by the root logger.

**Comment by jtherrmann** [comment]
Another complication is that if we delete the line:

```python3
rasterio.logging.getLogger().setLevel(rasterio.logging.WARN)
```

from `dem.py`, we will likely get too much log output from `rasterio` (I vaguely remember this being why we added that line to begin with).

This could be a good time to address https://github.com/ASFHyP3/hyp3-isce2/issues/10 to remove `rasterio`, or we could punt that and just implement a workaround for the excess log output. Does `rasterio` have its own logger whose level we could set? Or is it using the root logger directly?

**Comment by jhkennedy** [comment]
@jtherrmann when you're interacting with `rasterio.logging` you're hitting the root logger. Rasterio adds a `NullHandler` here:
https://github.com/rasterio/rasterio/blob/main/rasterio/__init__.py#L88-L94

and follows the expected logging configuration for python

**Comment by jtherrmann** [comment]
The reason for the excessive `rasterio` logging output is that `isce2` sets the root logger level to `DEBUG`: https://github.com/isce-framework/isce2/blob/a5630c12030c6ffc7e5f4106471a3e7a9961b438/defaults/logging/logging.conf#L10-L11

**Comment by jtherrmann** [comment]
So, to summarize, because `isce2` set the root logger to `DEBUG`, we got a bunch of extra log messages from `rasterio`, so we mistakenly set the root logger to `WARN` (we should have set the level only for the `rasterio.log` logger), which made our `log.info` messages disappear. So the solution is to (1) delete the line that sets the root logger to `WARN` in `dem.py` and (2) set the root logger level to `INFO` after `isce2` sets it to `DEBUG`. This allows our `log.info` messages to appear as expected, and gets rid of the excessive `rasterio` log output.
